#' @include utils.R
NULL

cols_padlocout <- readr::cols(
  system.number      = readr::col_character(),
  seqid              = readr::col_character(),
  system             = readr::col_character(),
  target.name        = readr::col_character(),
  hmm.accession      = readr::col_character(),
  hmm.name           = readr::col_character(),
  protein.name       = readr::col_character(),
  full.seq.E.value   = readr::col_character(),
  domain.iE.value    = readr::col_character(),
  target.coverage    = readr::col_character(),
  hmm.coverage       = readr::col_character(),
  start              = readr::col_character(),
  end                = readr::col_character(),
  strand             = readr::col_character(),
  target.description = readr::col_character(),
  relative.position  = readr::col_character(),
  contig.end         = readr::col_character(),
  all.domains        = readr::col_character(),
  best.hits          = readr::col_character()
)

cols_padlocout_master <- cols_c(list(
  readr::cols(genome.accession = readr::col_character()),
  cols_padlocout
))

#' Read PADLOC output files
#' @param path The path to a PADLOC output file (i.e. the files generated by
#' PADLOC ending in '*_padloc.csv').
#' @return A [tibble::tibble()].
#' @export
read_padlocout <- function(path) {
  cols <- cols_padlocout
  out <- readr::read_csv(path, col_names = names(cols$cols), col_types = cols,
                         progress = FALSE, skip = 1)
  out
}

#' Read PADLOC master output files
#' @param path The path to a PADLOC master output file (as generated by
#' [combine_padlocout()]).
#' @return A [tibble::tibble()].
#' @export
read_padlocout_master <- function(path) {
  cols <- cols_padlocout_master
  out <- readr::read_csv(path, col_names = names(cols$cols), col_types = cols,
                         progress = FALSE, skip = 1)
  out
}

#' Read multiple files
#' @param path A character vector of full path names; the default corresponds
#' to the working directory, [getwd()]. Tilde expansion (see [path.expand]) is
#' performed. Missing values will be ignored. Elements with a marked encoding
#' will be converted to the native encoding (and if that fails, considered
#' non-existent).
#' @param pattern An optional regular expression. Only file names which match
#' the regular expression will be returned.
#' @param func A function to use for reading.
#' @return A [list()], where each element is a [tibble::tibble()] holding
#' the contents of the file.
#' @export
multi_read <- function(path = ".", func, pattern = NULL) {
  func <- substitute(func)
  file_paths <- list.files(path, full.names = TRUE, pattern = pattern)
  # file_content <- purrr::map(.x = file_paths, .f = function(x) eval(func)(x))
  file_content <- purrr::map(.x = cli::cli_progress_along(file_paths), .f = function(i) eval(func)(file_paths[i]))
  file_names <- basename(file_paths)
  names(file_content) <- file_names
  file_content
}


