#' @include utils.R
NULL

cols_padlocout <- readr::cols(
  system.number      = readr::col_double(),
  seqid              = readr::col_character(),
  system             = readr::col_character(),
  target.name        = readr::col_character(),
  hmm.accession      = readr::col_character(),
  hmm.name           = readr::col_character(),
  protein.name       = readr::col_character(),
  full.seq.E.value   = readr::col_double(),
  domain.iE.value    = readr::col_double(),
  target.coverage    = readr::col_double(),
  hmm.coverage       = readr::col_double(),
  start              = readr::col_double(),
  end                = readr::col_double(),
  strand             = readr::col_character(),
  target.description = readr::col_character(),
  relative.position  = readr::col_double(),
  contig.end         = readr::col_character(),
  all.domains        = readr::col_character(),
  best.hits          = readr::col_character()
)

cols_padlocout_master <- cols_c(list(
  readr::cols(genome.accession = readr::col_character()),
  cols_padlocout
))

#' Read PADLOC output files
#' @param path The path to a PADLOC output file (i.e. the files generated by
#' PADLOC ending in '*_padloc.csv').
#' @return A [tibble::tibble()].
#' @export
read_padlocout <- function(path) {
  cols <- cols_padlocout
  out <- readr::read_csv(path, col_names = names(cols$cols), col_types = cols,
                         progress = FALSE, skip = 1)
  out
}

#' Read PADLOC master output files
#' @param path The path to a PADLOC master output file (as generated by
#' [combine_padlocout()]).
#' @return A [tibble::tibble()].
#' @export
read_padlocout_master <- function(path) {
  cols <- cols_padlocout_master
  out <- readr::read_csv(path, col_names = names(cols$cols), col_types = cols,
                         progress = FALSE, skip = 1)
  out
}

#' Read multiple PADLOC output files
#' @param path A character vector of full path names; the default corresponds
#' to the working directory, [getwd()]. Tilde expansion (see [path.expand]) is
#' performed. Missing values will be ignored. Elements with a marked encoding
#' will be converted to the native encoding (and if that fails, considered
#' non-existent).
#' @return A [list()], where each element is a [tibble::tibble()] holding
#' the contents of the file.
#' @export
multi_read_padlocout <- function(path) {
  out <- multi_read(path = path, func = read_padlocout, pattern = "*_padloc.csv", name = "Reading PADLOC output files")
  out
}

#' Read multiple PADLOC master output files
#' @param path A character vector of full path names; the default corresponds
#' to the working directory, [getwd()]. Tilde expansion (see [path.expand]) is
#' performed. Missing values will be ignored. Elements with a marked encoding
#' will be converted to the native encoding (and if that fails, considered
#' non-existent).
#' @return A [list()], where each element is a [tibble::tibble()] holding
#' the contents of the file.
#' @export
multi_read_padlocout_master <- function(path) {
  out <- multi_read(path = path, func = read_padlocout_master, pattern = "*_padloc.csv", name = "Reading PADLOC output files")
  out
}

