#' @include utils.R
NULL

cols_gff <- readr::cols(
  seqid      = readr::col_character(),
  source     = readr::col_character(),
  type       = readr::col_character(),
  start      = readr::col_double(),
  end        = readr::col_double(),
  score      = readr::col_character(),
  strand     = readr::col_character(),
  phase      = readr::col_character(),
  attributes = readr::col_character()
)

cols_gff_master <- cols_c(list(
  readr::cols(genome.accession = readr::col_character()),
  cols_gff
))

#' Read a GFF file
#' @param path A character vector of full path names; the default corresponds
#' to the working directory, [getwd()]. Tilde expansion (see [path.expand]) is
#' performed. Missing values will be ignored. Elements with a marked encoding
#' will be converted to the native encoding (and if that fails, considered
#' non-existent).
#' @export
read_gff <- function(path) {
  cols <- cols_gff
  out <- readr::read_tsv(path, col_names = names(cols$cols), col_types = cols,
                         progress = FALSE, comment = "#")
  out
}

#' Read multiple GFF files
#' @param path A character vector of full path names; the default corresponds
#' to the working directory, [getwd()]. Tilde expansion (see [path.expand]) is
#' performed. Missing values will be ignored. Elements with a marked encoding
#' will be converted to the native encoding (and if that fails, considered
#' non-existent).
#' @return A [list()], where each element is a [tibble::tibble()] holding
#' the contents of the file.
#' @export
multi_read_gff <- function(path, namefix = NULL) {
  out <- multi_read(path = path, func = read_gff, pattern = "*_genomic.gff",
                    barname = "Reading GFF files", namefix = namefix)
  out
}

#' Combine a list of GFF tables
#' @param gff_list A list of GFF tables (as read in by [multi_read_gff()]).
#' @return A combined GFF table, introducing a new row `genome_accession`,
#' which is derived from the names of the GFF tables in `padlocout_list`.
#' @export
combine_gff <- function(gff_list) {
  to_combine <- purrr::map(
    .x = cli::cli_progress_along(gff_list, name = "Combining GFF files"),
    .f = function(i) {
      # Check if there's a column for genome accession, and if not make one
      if (! "genome.accession" %in% names(gff_list[[i]])) {
        file_name <- names(gff_list[i])
        genome_accession <- stringr::str_remove(file_name, "_genomic.gff")
        x <- dplyr::mutate(gff_list[[i]], "genome.accession" = genome_accession)
        x <- dplyr::select(x, "genome.accession", dplyr::everything())
        x
      } else {
        gff_list[[i]]
      }
    }
  )
  combined <- dplyr::bind_rows(to_combine)
  combined
}

#' Write a GFF file
#' @param gff A GFF table as read in by [read_gff()], or a combined GFF table,
#' as generated by [combine_gff()]).
#' @export
write_gff <- function(gff) {
  readr::write_tsv(gff, col_names = FALSE)
}
