#' Combine a list of padlocout tables
#' @param padlocout_list A list of padlocout tables (as read in by
#' [multi_read_padlocout()]).
#' @return A combined padlocout table, introducing a new row `genome_accession`,
#' which is derived from the names of the padlocout tables in `padlocout_list`.
#' @export
combine_padlocout <- function(padlocout_list) {
  extra_col <- purrr::map(
    .x = cli::cli_progress_along(padlocout_list, name = "Combining PADLOC output"),
    .f = function(i) {
      file_name <- names(padlocout_list[i])
      genome_accession <- stringr::str_remove(file_name, "_protein_padloc.csv")
      x <- dplyr::mutate(padlocout_list[[i]], "genome.accession" = genome_accession)
      x <- dplyr::select(x, "genome.accession", dplyr::everything())
      x
    }
  )
  combined <- dplyr::bind_rows(extra_col)
  combined
}

#' Summarise how many of each system were identified
#' @param padlocout A padlocout table (as read in by [read_padlocout()]) or a
#' combined padlocout table (as generated by [combine_padlocout()])
#' @return A [tibble::tibble()] with columns `system` and `n`, where there is a
#' single row for each system summarising the number of times a system was
#' identified in the padlocout table.
#' @export
summarise_system_count <- function(padlocout) {
  grouped <- dplyr::group_by(padlocout, seqid, system)
  unique <- dplyr::distinct(grouped, system.number)
  grouped <- dplyr::group_by(unique, system)
  count <- dplyr::summarise(grouped, n = dplyr::n())
  count
}
