#' Summarise how many of each system were identified
#' @param padlocout A padlocout table (as read in by [read_padlocout()]) or a
#' combined padlocout table (as generated by [padlocout_combine()])
#' @return A [tibble::tibble()] with columns `system` and `n`, where there is a
#' single row for each system summarising the number of times a system was
#' identified in the padlocout table.
#' @export
summarise_system_count <- function(padlocout) {
  # grouped <- dplyr::group_by(padlocout, seqid, system)
  unique <- dplyr::distinct(padlocout, seqid, system, system.number)
  grouped <- dplyr::group_by(unique, system)
  count <- dplyr::summarise(grouped, n = dplyr::n())
  count
}

#' Summarise how many times specific proteins overlap
#' @param padlocout A padlocout table (as read in by [read_padlocout()]) or a
#' combined padlocout table (as generated by [padlocout_combine()])
#' @return A [tibble::tibble()].
#' @export
summarise_protein_overlap <- function(padlocout) {
  a <- dplyr::group_by(padlocout, seqid, relative.position)
  b <- dplyr::mutate(a, overlapping_proteins = paste0(unique(protein.name), collapse = "=="))
  c <- dplyr::group_by(b, overlapping_proteins)
  d <- dplyr::summarise(c, n = dplyr::n())
  e <- dplyr::arrange(d, desc(n))
  f <- dplyr::filter(e, grepl(pattern = "==", overlapping_proteins))
  f
}

#' Summarise how many times systems overlap
#' @param padlocout A padlocout table (as read in by [read_padlocout()]) or a
#' combined padlocout table (as generated by [padlocout_combine()])
#' @return A [tibble::tibble()].
#' @export
summarise_system_overlap <- function(padlocout) {
  a <- dplyr::group_by(padlocout, seqid, relative.position)
  b <- dplyr::mutate(
    a,
    overlapping_systems = paste0(unique(system), collapse = "=="),
    overlapping_num = paste0(unique(system.number), collapse = "==")
  )
  c <- dplyr::ungroup(b)
  d <- dplyr::distinct(c, seqid, overlapping_num, overlapping_systems)
  e <- dplyr::group_by(d, overlapping_systems)
  f <- dplyr::summarise(e, n = dplyr::n())
  g <- dplyr::arrange(f, desc(n))
  h <- dplyr::filter(g, grepl(pattern = "==", overlapping_systems))
  h
}
